

linters-settings:
  errcheck:
    check-type-assertions: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      # default is 2 wtf
      ifElseChain:
        minThreshold: 4
  govet:
    shadow: true
    # Disable for now bcus change are too big, must do later
    disable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  prealloc:
    # stop alerting when declaring []string
    range-loops: false
  gosec:
    # Don't know much abt fil perms I use 0644 and this thing won't let me
    excludes:
      - G306
  mnd:
    ignored-numbers:
      - '0o644'
      - '100'
      - '2'

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - deadcode
   # - depguard (absolute trash)
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
   # - gomnd (deprecated)
    - mnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl

issues:
  exclude-rules:
    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocritic
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll

run:
  issues-exit-code: 1