// (c) Jisin0

package omdb

import (
	"strings"

	"github.com/Jisin0/filmigo/internal/types"
)

// Result from the omc.log.Debug("using cached data")db.GetMovie function containing full data on a movie.
type Movie struct {
	// Title of the movie.
	Title string `json:"title"`
	// Year the movie was released.
	Year string `json:"year"`
	// Parental guidline rating for ex: R, PG etc.
	Rated string `json:"rated"`
	// Date on which the movie was released in the format 01 January 1950.
	Released string `json:"released"`
	// Runtime/Duration of the movie in minutes for ex. 120 min.
	Runtime string `json:"runtime"`
	// Genres of the movie ina string separated by commas for ex: Action, Comedy, Romance.
	Genres string `json:"genre"`
	// Name of the Director of the movie.
	Director string `json:"director"`
	// Writers of the movie separated by commas.
	Writers string `json:"writer"`
	// Actors/Stars of the movie separated by commas.
	Actors string `json:"actors"`
	// Plot of the movie.
	Plot string `json:"plot"`
	// List of languages separated by commas for ex: English, Spanish, Italian.
	Languages string `json:"language"`
	// Country of origin of the movie.
	Country string `json:"country"`
	// Awards won by the movie.
	Awards string `json:"awards"`
	// Poster image url of the movie.
	Poster string `json:"poster"`
	// Ratings of the movie from various sources.
	Ratings []Rating `json:"ratings"`
	// Metascore of the movie.
	Metascore string `json:"metascore"`
	// Rating of the movie from imdb, returned value is out of 10.
	ImdbRating string `json:"imdbrating"`
	// Number of votes the movie received on imdb.
	ImdbVotes string `json:"imdbvotes"`
	// Imdb id of the movie.
	ImdbID string `json:"imdbid"`
	// Type of title for ex: movie, series or episode.
	// Use omdb.ResultTypeXX values for reliablility.
	Type string `json:"type"`
	// DVD release date of the movie.
	DVD string `json:"dvd"`
	// Boxoffice income generated by the movie with it's currency.
	BoxOffice string `json:"boxoffice"`
	// Production company associated with the movie.
	Production string `json:"production"`
	// Any official website of the movie.
	Website string `json:"website"`
	// This value indicates wether a result was returned.
	// Value is True on success and False on failure (case sensitive).
	Response string `json:"response"`
	// Error message returned for failed queries.
	// This value should be checked to determine wether the reason for a failed call.
	Error string `json:"error"`
}

// Ensure *imdb.Movie satisfies shared movie interface
var _ types.Movie = (*Movie)(nil)

func (m *Movie) GetType() string {
	return m.Type
}

func (m *Movie) GetID() string {
	return m.ImdbID
}

func (m *Movie) GetURL() string {
	return "https://imdb.com/title/tt" + m.ImdbID
}

func (m *Movie) GetTitle() string {
	return m.Title
}

func (m *Movie) GetPosterURL() string {
	return m.Poster
}

func (m *Movie) GetGenres() []string {
	return strings.Split(m.Genres, ", ")
}

func (m *Movie) GetPlot() string {
	return m.Plot
}
